name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: install conan
      uses: turtlebrowser/get-conan@v1.0
    - name: install qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: "6.7.0"
    - name: conan profile
      run: conan profile detect && sudo apt-get install libudev-dev
    - name: setup
      run: make setup
    - name: build
      run: make build
