name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: turtlebrowser/get-conan@v1.0
    - uses: jurplel/install-qt-action@v6
    - name: conan profile
      run: conan profile detect && sudo apt-get install libudev-dev
    - name: setup
      run: make setup
    - name: build
      run: make build
